---
profile: iterate

shared:
  ingress_domain: "$TAP_DOMAIN"

contour:
  envoy:
    service:
      type: LoadBalancer

ceip_policy_disclosed: true

buildservice:
  kp_default_repository: "$REGISTRY_HOST/$REGISTRY_REPO/tap/build-service"
  kp_default_repository_username: "$REGISTRY_USER"
  kp_default_repository_password: "$REGISTRY_PASS"
  tanzunet_username: "$TANZUNET_USER"
  tanzunet_password: "$TANZUNET_PASS"
  enable_automatic_dependency_updates: false

supply_chain: basic

ootb_supply_chain_basic:
  registry:
    server: "$REGISTRY_HOST"
    repository: "$REGISTRY_REPO/workloads"
  gitops:
    ssh_secret: ""

metadata_store:
  app_service_type: LoadBalancer
